// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VroomAuto.DataAccess;

namespace VroomAuto.DataAccess.Migrations
{
    [DbContext(typeof(MyPageDbContext))]
    [Migration("20200417063410_InitialDataStructure")]
    partial class InitialDataStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VroomAuto.AppLogic.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufacutreDate")
                        .HasColumnType("Date");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("BrandName");

                    b.HasIndex("ClassName");

                    b.HasIndex("ModelName");

                    b.HasIndex("Status1");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.CarBrand", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.CarClass", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("CarClasses");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.CarModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.CarStatus", b =>
                {
                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Status");

                    b.ToTable("CarStatuses");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.History", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.HasIndex("UserID");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Type1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.UserType", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.Car", b =>
                {
                    b.HasOne("VroomAuto.AppLogic.Models.CarBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandName");

                    b.HasOne("VroomAuto.AppLogic.Models.CarClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassName");

                    b.HasOne("VroomAuto.AppLogic.Models.CarModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelName");

                    b.HasOne("VroomAuto.AppLogic.Models.CarStatus", "Status")
                        .WithMany()
                        .HasForeignKey("Status1");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.History", b =>
                {
                    b.HasOne("VroomAuto.AppLogic.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarID");

                    b.HasOne("VroomAuto.AppLogic.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("VroomAuto.AppLogic.Models.User", b =>
                {
                    b.HasOne("VroomAuto.AppLogic.Models.UserType", "Type")
                        .WithMany()
                        .HasForeignKey("Type1");
                });
#pragma warning restore 612, 618
        }
    }
}
